development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: form_template_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: form_template_production
